name: "Testing the build"
 
on:
  push:
    branches:
      - master
 
jobs:
  build:
    name: Build the app
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
 
      - name: Install dependencies
        run: |
           if [ -f package-lock.json ]; then
            npm ci
           else
            npm install
           fi
 
      - name: Build the app
        run: npm run build
